#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    # Calculate the count of positive, negative and zero values
    positive = len([num for num in arr if num > 0])
    negative = len([num for num in arr if num < 0])
    zero = len([num for num in arr if num == 0])

    # Calculate the ratios
    ratio_positive = round(positive / len(arr), 6) if len(arr) != 0 else 0
    ratio_negative = round(negative / len(arr), 6) if len(arr) != 0 else 0
    ratio_zero = round(zero / len(arr), 6) if len(arr) != 0 else 0

    # Print the ratios
    print(ratio_positive)
    print(ratio_negative)
    print(ratio_zero)

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
